// Generated by Wrangler by running `wrangler types`

interface Env {
	SANITY_STUDIO_API_VERSION: "2023-07-16";
	SANITY_STUDIO_DATASET: "production";
	SANITY_STUDIO_PROJECT_ID: "vg3sb730";
	SANITY_AUTH_TOKEN: string;
	PUBLIC_CLERK_PUBLISHABLE_KEY: string;
	CLERK_SECRET_KEY: string;
}
