// Generated by Wrangler by running `wrangler types`

interface Env {
	PUBLIC_CLERK_PUBLISHABLE_KEY: "pk_test_YWRlcXVhdGUtbW9uYXJjaC01NS5jbGVyay5hY2NvdW50cy5kZXYk";
	CLERK_SECRET_KEY: string;
	SANITY_STUDIO_API_VERSION: string;
	SANITY_STUDIO_DATASET: string;
	SANITY_STUDIO_PROJECT_ID: string;
	SANITY_AUTH_TOKEN: string;
}
