// Generated by Wrangler by running `wrangler types`

interface Env {
	PUBLIC_CLERK_PUBLISHABLE_KEY: "pk_test_aHVtb3JvdXMta2luZ2Zpc2gtNzUuY2xlcmsuYWNjb3VudHMuZGV2JA";
	CLERK_SECRET_KEY: string;
	SANITY_STUDIO_API_VERSION: string;
	SANITY_STUDIO_DATASET: string;
	SANITY_STUDIO_PROJECT_ID: string;
}
