name: Feature
description: Create an Issue to track a Feature.
labels: ["website"]
type: Feature
projects: ["grief-matters/1"]
body:
  - type: markdown
    attributes:
      value: |
        A **Feature** represents something new that unlocks value for us or our users.

        If something is broken, then create a **Bug** issue instead. 

        If this is to change or improve something that already exists, consider creating an **Enhancement** issue instead.
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: Describe the Feature. What problem are we trying to solve? What value will this unlock for us or our users?
      placeholder: |
        e.g...
        By adding X our users will be able to do Y, this helps us with Z
    validations:
      required: true
  - type: textarea
    id: considerations
    attributes:
      label: Considerations And Supporting Info
      description: Is there related information, existing features, screenshots, anything that might be relevant to arriving at the right solution?
      placeholder: |
        e.g...
        www.example.com provides this functionality, as a competitor, we should offer something similar. Here are some screenshots of how their feature looks...
    validations:
      required: false
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What is the "Definition of Done" for this Feature? What should exist for the feature to be considered complete?
      placeholder: |
        e.g...
        1. User should be able to submit a thing
        2. User should receive feedback that they have done a thing
        3. Thing done should be reflected in an updated UI
    validations:
      required: true
