name: Bug
description: Create an Issue to track a Bug.
labels: ["bug", "website"]
projects: ["grief-matters/1"]
body:
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: Describe the bug
      placeholder: |
        e.g. The something button does not activate the other thing...
    validations:
      required: true
  - type: textarea
    id: bug-repro
    attributes:
      label: Steps to Reproduce
      description: Describe the steps to make the bug occur
      placeholder: |
        e.g...
        1. Go to this link
        2. Do this thing
        3. Watch it explode 💥
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: Describe what you are expecting to happen
      placeholder: |
        I am expecting...
      value: |
        I am expecting...
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: other-info
    attributes:
      label: Any relevant info
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
      placeholder: |
        Any other relevant information...
    validations:
      required: false
