import type { InternetResourceType } from "@model/internetResource";

export const resourceTypeBorderColorMap: Record<InternetResourceType, string> =
  {
    app: "border-blue-500",
    article: "border-fuchsia-500",
    blog: "border-red-500",
    book: "border-orange-500",
    booklet: "border-amber-500",
    brochure: "border-yellow-400",
    course: "border-sky-500",
    forum: "border-fuchsia-500",
    memorial: "border-indigo-500",
    peerSupport: "border-rose-500",
    podcast: "border-violet-500",
    podcastEpisode: "border-violet-500",
    story: "border-teal-500",
    supportGroup: "border-purple-500",
    therapyResource: "border-cyan-500",
    video: "border-green-500",
    webinar: "border-green-500",
    website: "border-blue-500",
  };

export const resourceTypeTextColorMap: Record<InternetResourceType, string> = {
  app: "text-blue-500",
  article: "text-fuchsia-500",
  blog: "text-red-500",
  book: "text-orange-500",
  booklet: "text-amber-500",
  brochure: "text-yellow-400",
  course: "text-sky-500",
  forum: "text-fuchsia-500",
  memorial: "text-indigo-500",
  peerSupport: "text-rose-500",
  podcast: "text-violet-500",
  podcastEpisode: "text-violet-500",
  story: "text-teal-500",
  supportGroup: "text-purple-500",
  therapyResource: "text-cyan-500",
  video: "text-green-500",
  webinar: "text-green-500",
  website: "text-blue-500",
};

export const resourceTypeBgColorMap: Record<InternetResourceType, string> = {
  app: "bg-blue-500",
  article: "bg-fuchsia-500",
  blog: "bg-red-500",
  book: "bg-orange-500",
  booklet: "bg-amber-500",
  brochure: "bg-yellow-400",
  course: "bg-sky-500",
  forum: "bg-fuchsia-500",
  memorial: "bg-indigo-500",
  peerSupport: "bg-rose-500",
  podcast: "bg-violet-500",
  podcastEpisode: "bg-violet-500",
  story: "bg-teal-500",
  supportGroup: "bg-purple-500",
  therapyResource: "bg-cyan-500",
  video: "bg-green-500",
  webinar: "bg-green-500",
  website: "bg-blue-500",
};
