import type { InternetResourceType } from "@model/common";

export const resourceTypeBorderColorMap: Record<InternetResourceType, string> =
  {
    app: "border-blue-300",
    article: "border-fuchsia-300",
    blog: "border-blue-300",
    book: "border-blue-300",
    booklet: "border-blue-300",
    brochure: "border-blue-300",
    course: "border-blue-300",
    forum: "border-blue-300",
    memorial: "border-blue-300",
    peerSupport: "border-blue-300",
    podcast: "border-blue-300",
    podcastEpisode: "border-blue-300",
    story: "border-teal-300",
    supportGroup: "border-blue-300",
    therapyResource: "border-blue-300",
    video: "border-blue-300",
    webinar: "border-blue-300",
    website: "border-blue-300",
  };

export const resourceTypeTextColorMap: Record<InternetResourceType, string> = {
  app: "text-blue-500",
  article: "text-fuchsia-500",
  blog: "text-blue-500",
  book: "text-blue-500",
  booklet: "text-blue-500",
  brochure: "text-blue-500",
  course: "text-blue-500",
  forum: "text-blue-500",
  memorial: "text-blue-500",
  peerSupport: "text-blue-500",
  podcast: "text-blue-500",
  podcastEpisode: "text-blue-500",
  story: "text-teal-500",
  supportGroup: "text-blue-500",
  therapyResource: "text-blue-500",
  video: "text-blue-500",
  webinar: "text-blue-500",
  website: "text-blue-500",
};

export const resourceTypeBgColorMap: Record<InternetResourceType, string> = {
  app: "bg-blue-500",
  article: "bg-fuchsia-500",
  blog: "bg-blue-500",
  book: "bg-blue-500",
  booklet: "bg-blue-500",
  brochure: "bg-blue-500",
  course: "bg-blue-500",
  forum: "bg-blue-500",
  memorial: "bg-blue-500",
  peerSupport: "bg-blue-500",
  podcast: "bg-blue-500",
  podcastEpisode: "bg-blue-500",
  story: "bg-teal-500",
  supportGroup: "bg-blue-500",
  therapyResource: "bg-blue-500",
  video: "bg-blue-500",
  webinar: "bg-blue-500",
  website: "bg-blue-500",
};
