name: Cloudflare Deploy Hook

on:
  schedule:
    # Runs at 7:00 AM UTC every day (1am EDT)
    - cron: "0 7 * * *"
  workflow_dispatch: # Allows for manual trigger via GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Call Cloudflare Deploy Hook
        run: |
          curl -X POST ${{ secrets.DEPLOY_HOOK_URL }}
